import { NodeType, NodeCategory } from '../types/workflow';

export interface NodeDefinition {
  type: NodeType;
  label: string;
  category: NodeCategory;
  description: string;
  icon: string; // Lucide icon name
  defaultProperties: Record<string, any>;
  reactFlowType?: string; // 'customNode' | 'conditionNode' | 'loopNode'
}

export const NODE_REGISTRY: Record<NodeType, NodeDefinition> = {
  // Scrapers (100% Free, Keyless)
  youtube_scraper: {
    type: 'youtube_scraper',
    label: 'YouTube Scraper',
    category: 'scrapers',
    description: 'Extract transcripts, video info, search results, or comments with zero API keys via youtubei.js',
    icon: 'PlaySquare',
    reactFlowType: 'scraperNode',
    defaultProperties: {
      headless: true,
      engine: 'browser', // 'browser' | 'youtubei_js'
      mode: 'search', // 'search' | 'video_details' | 'video_script' | 'comments' | 'channel_videos'
      query: 'web scraping automation',
      url: '',
      channel: '',
      scriptLanguage: 'en',
      scriptFormat: 'timestamped',
      maxResults: 15,
      autoScrollPasses: 3,
      scrollDelay: 1200,
      sortBy: 'relevance',
      outputVariable: 'youtubeResults',
      itemVariable: 'video',
      exportFormat: 'none',
      exportFilename: 'youtube_data',
      autoCloseTab: true,
      browserFallback: false,
    },
  },
  instagram_scraper: {
    type: 'instagram_scraper',
    label: 'Instagram Scraper',
    category: 'scrapers',
    description: 'Extract public profile bios, follower counts, post captions, and media',
    icon: 'Camera',
    reactFlowType: 'scraperNode',
    defaultProperties: {
      headless: true,
      engine: 'browser',
      mode: 'profile_posts',
      target: 'nature',
      maxResults: 12,
      autoScrollPasses: 3,
      scrollDelay: 1500,
      outputVariable: 'instagramResults',
      itemVariable: 'post',
      exportFormat: 'none',
      exportFilename: 'instagram_data',
      autoCloseTab: true,
    },
  },
  reddit_scraper: {
    type: 'reddit_scraper',
    label: 'Reddit Scraper',
    category: 'scrapers',
    description: 'Fast keyless extraction of subreddits, posts, search queries, or comments',
    icon: 'Flame',
    reactFlowType: 'scraperNode',
    defaultProperties: {
      headless: true,
      engine: 'snoowrap_api', // 'snoowrap_api' | 'browser'
      mode: 'subreddit',
      subreddit: 'webscraping',
      query: '',
      postUrl: '',
      sortBy: 'hot',
      timeFilter: 'all',
      maxResults: 25,
      outputVariable: 'redditResults',
      itemVariable: 'redditItem',
      exportFormat: 'none',
      exportFilename: 'reddit_data',
      autoCloseTab: true,
    },
  },
  linkedin_scraper: {
    type: 'linkedin_scraper',
    label: 'LinkedIn Scraper',
    category: 'scrapers',
    description: 'Extract public job postings, job details, and public profile data',
    icon: 'Briefcase',
    reactFlowType: 'scraperNode',
    defaultProperties: {
      headless: true,
      engine: 'browser',
      mode: 'jobs_search',
      keywords: 'Software Engineer',
      location: 'Remote',
      url: '',
      maxResults: 15,
      autoScrollPasses: 2,
      scrollDelay: 1500,
      outputVariable: 'linkedinResults',
      itemVariable: 'job',
      exportFormat: 'none',
      exportFilename: 'linkedin_data',
      autoCloseTab: true,
    },
  },
  amazon_scraper: {
    type: 'amazon_scraper',
    label: 'Amazon Scraper',
    category: 'scrapers',
    description: 'Extract product search listings, prices, ratings, and customer reviews',
    icon: 'ShoppingCart',
    reactFlowType: 'scraperNode',
    defaultProperties: {
      headless: true,
      engine: 'browser', // 'browser' | 'amazon_buddy'
      mode: 'search',
      query: 'mechanical keyboard',
      productUrl: '',
      domain: 'com',
      minPrice: '',
      maxPrice: '',
      primeOnly: false,
      maxResults: 20,
      autoScrollPasses: 2,
      scrollDelay: 1200,
      outputVariable: 'amazonResults',
      itemVariable: 'product',
      exportFormat: 'none',
      exportFilename: 'amazon_data',
      autoCloseTab: true,
    },
  },
  twitter_scraper: {
    type: 'twitter_scraper',
    label: 'X (Twitter) Scraper',
    category: 'scrapers',
    description: 'Extract public tweets, user feeds, search results, and engagement stats',
    icon: 'AtSign',
    reactFlowType: 'scraperNode',
    defaultProperties: {
      headless: true,
      engine: 'twitter_scraper', // 'twitter_scraper' (@the-convocation/twitter-scraper) | 'browser'
      mode: 'profile_tweets',
      username: 'OpenAI',
      query: '',
      maxResults: 15,
      autoScrollPasses: 3,
      scrollDelay: 1500,
      outputVariable: 'twitterResults',
      itemVariable: 'tweet',
      exportFormat: 'none',
      exportFilename: 'twitter_data',
      autoCloseTab: true,
    },
  },
  google_search_scraper: {
    type: 'google_search_scraper',
    label: 'Google Search Scraper',
    category: 'scrapers',
    description: 'Scrape organic Google search results, snippets, titles, and URLs',
    icon: 'Search',
    reactFlowType: 'scraperNode',
    defaultProperties: {
      headless: true,
      engine: 'browser', // 'browser' | 'google_sr'
      mode: 'organic_search',
      query: 'browser automation extensions',
      pages: 1,
      maxResults: 10,
      country: '',
      language: '',
      outputVariable: 'googleResults',
      itemVariable: 'searchResult',
      exportFormat: 'none',
      exportFilename: 'google_results',
      autoCloseTab: true,
    },
  },

  // Browser
  navigate: {
    type: 'navigate',
    label: 'Navigate',
    category: 'browser',
    description: 'Go to a web page URL',
    icon: 'Globe',
    defaultProperties: {
      url: 'https://example.com',
      waitUntil: 'load',
      openInNewTab: false,
      timeout: 30000,
    },
  },
  back: {
    type: 'back',
    label: 'Back',
    category: 'browser',
    description: 'Navigate backward in history',
    icon: 'ArrowLeft',
    defaultProperties: {},
  },
  forward: {
    type: 'forward',
    label: 'Forward',
    category: 'browser',
    description: 'Navigate forward in history',
    icon: 'ArrowRight',
    defaultProperties: {},
  },
  reload: {
    type: 'reload',
    label: 'Reload',
    category: 'browser',
    description: 'Reload the current page',
    icon: 'RotateCw',
    defaultProperties: {},
  },
  new_tab: {
    type: 'new_tab',
    label: 'New Tab',
    category: 'browser',
    description: 'Open a new browser tab',
    icon: 'PlusSquare',
    defaultProperties: {
      url: 'about:blank',
    },
  },
  close_tab: {
    type: 'close_tab',
    label: 'Close Tab',
    category: 'browser',
    description: 'Close the current or target tab',
    icon: 'XSquare',
    defaultProperties: {
      closeTarget: 'current',
      tabIndex: 0,
      urlPattern: '',
    },
  },
  switch_tab: {
    type: 'switch_tab',
    label: 'Switch Tab',
    category: 'browser',
    description: 'Switch active browser tab',
    icon: 'Layers',
    defaultProperties: {
      tabTarget: 'next',
      tabIndex: 0,
      urlPattern: '',
      titlePattern: '',
    },
  },

  // Interaction
  click: {
    type: 'click',
    label: 'Click',
    category: 'interaction',
    description: 'Click an element on the webpage',
    icon: 'MousePointer',
    defaultProperties: {
      selector: '',
      clickType: 'left',
      timeout: 10000,
    },
  },
  type_text: {
    type: 'type_text',
    label: 'Type Text',
    category: 'interaction',
    description: 'Type text or variables into an input field',
    icon: 'Type',
    defaultProperties: {
      selector: '',
      text: '',
      clearExisting: true,
      typingDelay: 0,
      timeout: 10000,
    },
  },
  clear_input: {
    type: 'clear_input',
    label: 'Clear Input',
    category: 'interaction',
    description: 'Clear the contents of an input element',
    icon: 'Delete',
    defaultProperties: {
      selector: '',
      timeout: 10000,
    },
  },
  hover: {
    type: 'hover',
    label: 'Hover',
    category: 'interaction',
    description: 'Hover mouse cursor over an element',
    icon: 'Pointer',
    defaultProperties: {
      selector: '',
      timeout: 10000,
    },
  },
  press_key: {
    type: 'press_key',
    label: 'Press Key',
    category: 'interaction',
    description: 'Simulate pressing a keyboard key (e.g. Enter)',
    icon: 'Keyboard',
    defaultProperties: {
      key: 'Enter',
      selector: '',
    },
  },
  scroll: {
    type: 'scroll',
    label: 'Scroll',
    category: 'interaction',
    description: 'Scroll the page or a container element',
    icon: 'ChevronsDown',
    defaultProperties: {
      direction: 'down',
      amount: 400,
      smooth: true,
    },
  },
  smart_scroll: {
    type: 'smart_scroll',
    label: 'Smart Scroll',
    category: 'interaction',
    description: 'Smoothly scroll until bottom, element appears, or N iterations with live step progress',
    icon: 'ChevronsDown',
    defaultProperties: {
      mode: 'to_bottom', // 'to_bottom' | 'to_element' | 'distance'
      selector: '',
      distance: 600,
      maxScrolls: 5,
      scrollSpeed: 'normal', // 'slow' | 'normal' | 'fast' | 'instant' | 'custom'
      scrollDelay: 800,
      outputVariable: 'scrollResult',
    },
  },
  select_dropdown: {
    type: 'select_dropdown',
    label: 'Select Dropdown',
    category: 'interaction',
    description: 'Choose an option in a select dropdown',
    icon: 'ListFilter',
    defaultProperties: {
      selector: '',
      selectionType: 'value',
      value: '',
    },
  },
  drag_and_drop: {
    type: 'drag_and_drop',
    label: 'Drag & Drop',
    category: 'interaction',
    description: 'Drag element to another element target',
    icon: 'Move',
    defaultProperties: {
      sourceSelector: '',
      targetSelector: '',
    },
  },

  // Wait
  wait: {
    type: 'wait',
    label: 'Wait',
    category: 'wait',
    description: 'Pause execution for specified duration',
    icon: 'Clock',
    defaultProperties: {
      duration: 2000,
      timeout: 2000,
      unit: 'ms',
      timerName: '',
      stopCondition: {
        enabled: false,
        type: 'text',
        text: '',
        matchMode: 'partial',
        caseSensitive: false,
        selector: '',
        operator: 'equals',
        leftValue: '',
        rightValue: '',
      },
    },
  },
  wait_for_element: {
    type: 'wait_for_element',
    label: 'Wait For Element',
    category: 'wait',
    description: 'Wait until element appears and is visible',
    icon: 'Search',
    defaultProperties: {
      selector: '',
      timeout: 10000,
      visible: true,
      enabled: false,
    },
  },
  wait_for_text: {
    type: 'wait_for_text',
    label: 'Wait For Text',
    category: 'wait',
    description: 'Wait until specific text appears on the page',
    icon: 'FileText',
    defaultProperties: {
      text: '',
      selector: '',
      timeout: 10000,
      matchMode: 'partial',
      caseSensitive: false,
    },
  },
  wait_for_navigation: {
    type: 'wait_for_navigation',
    label: 'Wait For Navigation',
    category: 'wait',
    description: 'Wait for page URL change or navigation to complete',
    icon: 'Compass',
    defaultProperties: {
      urlPattern: '',
      timeout: 15000,
    },
  },

  // Extraction
  extract_text: {
    type: 'extract_text',
    label: 'Extract Text',
    category: 'extraction',
    description: 'Extract text content from an element',
    icon: 'FileText',
    defaultProperties: {
      selector: '',
      outputVariable: 'extractedText',
      timeout: 10000,
    },
  },
  extract_attribute: {
    type: 'extract_attribute',
    label: 'Extract Attribute',
    category: 'extraction',
    description: 'Extract an attribute like href, src, or value',
    icon: 'Tag',
    defaultProperties: {
      selector: '',
      attribute: 'href',
      outputVariable: 'extractedAttr',
      timeout: 10000,
    },
  },
  extract_html: {
    type: 'extract_html',
    label: 'Extract HTML',
    category: 'extraction',
    description: 'Extract outer or inner HTML from an element',
    icon: 'Code',
    defaultProperties: {
      selector: '',
      mode: 'outer',
      outputVariable: 'extractedHtml',
    },
  },
  extract_table: {
    type: 'extract_table',
    label: 'Extract Table',
    category: 'extraction',
    description: 'Parse HTML table into structured JSON rows',
    icon: 'Table',
    defaultProperties: {
      selector: 'table',
      outputVariable: 'tableData',
    },
  },
  extract_multiple: {
    type: 'extract_multiple',
    label: 'Extract Multiple Elements',
    category: 'extraction',
    description: 'Extract text or attributes from all matching elements into an array with inline loop body',
    icon: 'ListChecks',
    reactFlowType: 'iteratorNode',
    defaultProperties: {
      selector: '',
      attribute: '',
      itemVariable: 'currentElement',
      outputVariable: 'extractedList',
      timeout: 10000,
      exportToFile: false,
      exportFormat: 'csv', // 'csv' | 'xlsx' | 'json' | 'tsv'
      exportFilename: 'extracted_items',
    },
  },
  crawl_pagination: {
    type: 'crawl_pagination',
    label: 'Auto-Crawler (Pagination)',
    category: 'extraction',
    description: 'Crawls N pages via Next button or infinite scroll, appending rows into a single dataset',
    icon: 'Layers',
    reactFlowType: 'iteratorNode',
    defaultProperties: {
      mode: 'auto_detect',
      itemSelector: '',
      nextButtonSelector: '',
      attribute: '',
      maxPages: 5,
      pageDelay: 1500,
      stopOnNoNewItems: true,
      deduplicate: true,
      itemVariable: 'crawledItem',
      outputVariable: 'crawledDataset',
      totalExtractedVariable: 'totalCrawledItems',
      exportToFile: false,
      exportFormat: 'csv', // 'csv' | 'xlsx' | 'json' | 'tsv'
      exportFilename: 'crawled_dataset',
    },
  },
  extract_links: {
    type: 'extract_links',
    label: 'Extract Links',
    category: 'extraction',
    description: 'Scrape all hyperlinks with their text and URLs',
    icon: 'Link',
    defaultProperties: {
      selector: '',
      outputVariable: 'extractedLinks',
      timeout: 10000,
    },
  },
  extract_image: {
    type: 'extract_image',
    label: 'Extract Image',
    category: 'extraction',
    description: 'Extract image URL or base64 data from an element, background, or page',
    icon: 'Image',
    reactFlowType: 'iteratorNode',
    defaultProperties: {
      selector: 'img',
      mode: 'single', // 'single' | 'multiple'
      asBase64: false,
      includeBackground: true,
      itemVariable: 'currentImage',
      outputVariable: 'extractedImage',
      timeout: 10000,
    },
  },
  extract_all_images: {
    type: 'extract_all_images',
    label: 'Find All Images',
    category: 'extraction',
    description: 'Find and extract all images from the page or container with inline loop body',
    icon: 'Images',
    reactFlowType: 'iteratorNode',
    defaultProperties: {
      containerSelector: '',
      includeBackground: true,
      asBase64: false,
      minWidth: 10,
      minHeight: 10,
      maxImages: 100,
      itemVariable: 'currentImage',
      outputVariable: 'allImages',
      timeout: 10000,
    },
  },
  scrape_elements: {
    type: 'scrape_elements',
    label: 'Scrape Elements (Product Cards)',
    category: 'extraction',
    description: 'Extract structured multi-field cards (title, price, image, link, paragraphs) from repeating elements with loop body and file export',
    icon: 'LayoutGrid',
    reactFlowType: 'iteratorNode',
    defaultProperties: {
      containerSelector: '.product-card',
      fields: [
        { name: 'title', selector: 'h2, h3, h4, .title, [class*="title"]', attribute: 'text' },
        { name: 'price', selector: '.price, [class*="price"]', attribute: 'text' },
        { name: 'image', selector: 'img', attribute: 'src' },
        { name: 'link', selector: 'a', attribute: 'href' },
        { name: 'description', selector: 'p', attribute: 'paragraphs' },
      ],
      itemVariable: 'currentProduct',
      itemExtractField: 'all', // 'all' (whole card object) | 'link' | 'title' | 'price' | 'image' | 'description' | custom field
      itemExtractCustomField: '',
      outputVariable: 'scrapedProducts',
      exportToFile: false,
      exportFormat: 'csv',
      exportFilename: 'scraped_products',
      excludeEmpty: false,
      filterEmptyMode: 'any',
      // Post-Processing & Normalization
      postProcessingEnabled: false,
      urlBasePrefix: '',
      urlTargetFields: ['link'],
      stripUrlQueryParams: false,
      stripAllQueryParams: false,
      cleanPrice: false,
      priceMode: 'number_only', // 'number_only' | 'strip_symbols'
      formatDate: false,
      dateMode: 'iso_date', // 'iso_date' | 'iso_datetime' | 'timestamp'
      // Pattern Filter Condition ("if url in this pattern then only")
      patternFilterEnabled: false,
      patternFilterField: 'link',
      patternFilterAction: 'include_only', // 'include_only' | 'exclude_matching'
      patternFilterMode: 'contains', // 'contains' | 'regex' | 'starts_with' | 'ends_with'
      patternFilterValue: '',
      timeout: 10000,
    },
  },
  firecrawl: {
    type: 'firecrawl',
    label: 'Firecrawl (Keyless)',
    category: 'extraction',
    description: 'Convert any webpage into clean LLM-ready markdown or search & scrape using keyless Firecrawl API',
    icon: 'Flame',
    defaultProperties: {
      mode: 'scrape',
      url: '{{currentUrl}}',
      searchQuery: '',
      formats: ['markdown'],
      onlyMainContent: true,
      waitFor: 1000,
      apiKey: '',
      apiUrl: 'https://api.firecrawl.dev/v1',
      outputVariable: 'firecrawlMarkdown',
      fallbackToBrowser: true,
    },
  },

  // Logic
  condition: {
    type: 'condition',
    label: 'Condition',
    category: 'logic',
    description: 'Branch workflow execution based on condition',
    icon: 'GitBranch',
    reactFlowType: 'conditionNode',
    defaultProperties: {
      leftValue: '',
      operator: 'equals',
      rightValue: '',
      caseSensitive: false,
    },
  },
  contains: {
    type: 'contains',
    label: 'Contains',
    category: 'logic',
    description: 'Check whether an element is present on the page (TRUE / FALSE branches)',
    icon: 'SearchCheck',
    reactFlowType: 'containsNode',
    defaultProperties: {
      selector: '',
      matchMode: 'element',
      text: '',
      textMatchMode: 'partial',
      caseSensitive: false,
      visibleOnly: true,
      timeout: 5000,
      outputVariable: 'elementPresent',
    },
  },
  contains_text: {
    type: 'contains_text',
    label: 'Contains Text',
    category: 'logic',
    description: 'Check whether a particular text exists on the page (TRUE / FALSE branches)',
    icon: 'FileText',
    reactFlowType: 'containsNode',
    defaultProperties: {
      text: '',
      selector: '',
      matchMode: 'partial',
      caseSensitive: false,
      timeout: 3000,
      outputVariable: 'containsText',
    },
  },
  and: {
    type: 'and',
    label: 'AND',
    category: 'logic',
    description: 'Combines multiple branches: requires ALL incoming branches to be TRUE / complete before proceeding',
    icon: 'GitMerge',
    reactFlowType: 'logicGateNode',
    defaultProperties: {
      gate: 'AND',
      outputVariable: 'andResult',
      mode: 'combine_branches',
    },
  },
  or: {
    type: 'or',
    label: 'OR',
    category: 'logic',
    description: 'Combines multiple branches: continues as soon as ANY incoming branch is TRUE / complete (race condition)',
    icon: 'GitFork',
    reactFlowType: 'logicGateNode',
    defaultProperties: {
      gate: 'OR',
      outputVariable: 'orResult',
      mode: 'combine_branches',
    },
  },
  nand: {
    type: 'nand',
    label: 'NAND',
    category: 'logic',
    description: 'Negated AND: Continues unless ALL incoming branches are TRUE',
    icon: 'Ban',
    reactFlowType: 'logicGateNode',
    defaultProperties: {
      gate: 'NAND',
      outputVariable: 'nandResult',
      mode: 'combine_branches',
    },
  },
  nor: {
    type: 'nor',
    label: 'NOR',
    category: 'logic',
    description: 'Negated OR: Continues only when ALL incoming branches are FALSE',
    icon: 'CircleSlash',
    reactFlowType: 'logicGateNode',
    defaultProperties: {
      gate: 'NOR',
      outputVariable: 'norResult',
      mode: 'combine_branches',
    },
  },
  logic_and: {
    type: 'logic_and',
    label: 'AND',
    category: 'logic',
    description: 'Combines multiple branches: requires ALL incoming branches to be TRUE / complete before proceeding',
    icon: 'GitMerge',
    reactFlowType: 'logicGateNode',
    defaultProperties: {
      gate: 'AND',
      outputVariable: 'andResult',
      mode: 'combine_branches',
    },
  },
  logic_or: {
    type: 'logic_or',
    label: 'OR',
    category: 'logic',
    description: 'Combines multiple branches: continues as soon as ANY incoming branch is TRUE / complete (race condition)',
    icon: 'GitFork',
    reactFlowType: 'logicGateNode',
    defaultProperties: {
      gate: 'OR',
      outputVariable: 'orResult',
      mode: 'combine_branches',
    },
  },
  logic_nand: {
    type: 'logic_nand',
    label: 'NAND',
    category: 'logic',
    description: 'Negated AND: Continues unless ALL incoming branches are TRUE',
    icon: 'Ban',
    reactFlowType: 'logicGateNode',
    defaultProperties: {
      gate: 'NAND',
      outputVariable: 'nandResult',
      mode: 'combine_branches',
    },
  },
  logic_nor: {
    type: 'logic_nor',
    label: 'NOR',
    category: 'logic',
    description: 'Negated OR: Continues only when ALL incoming branches are FALSE',
    icon: 'CircleSlash',
    reactFlowType: 'logicGateNode',
    defaultProperties: {
      gate: 'NOR',
      outputVariable: 'norResult',
      mode: 'combine_branches',
    },
  },
  loop: {
    type: 'loop',
    label: 'Loop',
    category: 'logic',
    description: 'Repeat connected downstream nodes N times',
    icon: 'Repeat',
    reactFlowType: 'loopNode',
    defaultProperties: {
      count: 3,
    },
  },
  for_each: {
    type: 'for_each',
    label: 'For Each',
    category: 'logic',
    description: 'Iterate through an array of items',
    icon: 'List',
    reactFlowType: 'loopNode',
    defaultProperties: {
      array: '{{items}}',
    },
  },
  async_parallel: {
    type: 'async_parallel',
    label: 'Async Parallel',
    category: 'logic',
    description: 'Execute multiple workflow branches concurrently at the same time with error tolerance and throttling',
    icon: 'Zap',
    reactFlowType: 'asyncParallelNode',
    defaultProperties: {
      mode: 'all', // 'all' | 'settled' | 'race'
      branches: [
        { id: 'branch_1', name: 'Branch 1' },
        { id: 'branch_2', name: 'Branch 2' },
      ],
      maxConcurrency: 0,
      timeoutMs: 30000,
      continueOnError: false,
      mergeStrategy: 'merge',
      outputVariable: 'parallelResults',
    },
  },
  switch_case: {
    type: 'switch_case',
    label: 'Switch Case',
    category: 'logic',
    description: 'Branch execution based on matching value against multiple case outputs',
    icon: 'GitFork',
    reactFlowType: 'switchNode',
    defaultProperties: {
      expression: '{{status}}',
      cases: [
        { id: 'case_0', value: 'success', label: 'Success' },
        { id: 'case_1', value: 'error', label: 'Error' },
      ],
      matchMode: 'equals', // 'equals' | 'contains' | 'starts_with' | 'regex'
      caseSensitive: false,
      outputVariable: 'matchedCase',
    },
  },
  while_loop: {
    type: 'while_loop',
    label: 'While Loop',
    category: 'logic',
    description: 'Repeat connected downstream nodes while a condition remains true',
    icon: 'RefreshCw',
    reactFlowType: 'loopNode',
    defaultProperties: {
      leftValue: '',
      operator: 'equals',
      rightValue: '',
      caseSensitive: false,
      maxIterations: 50,
      delayBetweenMs: 500,
      outputVariable: 'whileIteration',
    },
  },
  retry_block: {
    type: 'retry_block',
    label: 'Retry Block',
    category: 'logic',
    description: 'Retry downstream steps or operations with configurable backoff upon failure',
    icon: 'RotateCcw',
    defaultProperties: {
      maxRetries: 3,
      backoffMode: 'exponential', // 'fixed' | 'linear' | 'exponential'
      retryDelayMs: 1000,
      retryCondition: 'on_error', // 'on_error' | 'custom_condition'
      leftValue: '',
      operator: 'equals',
      rightValue: '',
      outputVariable: 'retryInfo',
    },
  },
  rate_limiter: {
    type: 'rate_limiter',
    label: 'Rate Limiter',
    category: 'logic',
    description: 'Throttle execution rate and inject human-like jitter delays to prevent rate limits or bot bans',
    icon: 'Gauge',
    defaultProperties: {
      mode: 'jitter_range', // 'jitter_range' | 'requests_per_minute' | 'fixed_delay'
      minJitterMs: 1000,
      maxJitterMs: 3000,
      requestsPerMinute: 30,
      fixedDelayMs: 1500,
      outputVariable: 'throttledMs',
    },
  },
  manual_approval: {
    type: 'manual_approval',
    label: 'Manual Approval',
    category: 'logic',
    description: 'Pause execution and prompt human operator for confirmation, CAPTCHA solve, or input',
    icon: 'UserCheck',
    defaultProperties: {
      promptMessage: 'Please inspect the page or solve CAPTCHA, then click Resume.',
      inputType: 'confirm', // 'confirm' | 'text' | 'select'
      selectOptions: 'Approve, Reject',
      defaultValue: '',
      timeoutSeconds: 0,
      outputVariable: 'approvalResponse',
    },
  },
  error_handler: {
    type: 'error_handler',
    label: 'Error Handler',
    category: 'logic',
    description: 'Catch and handle errors from chosen nodes without stopping the workflow',
    icon: 'ShieldAlert',
    reactFlowType: 'errorHandlerNode',
    defaultProperties: {
      watchMode: 'chosen',
      watchedNodeIds: [],
      action: 'catch_and_continue',
      outputVariable: 'lastError',
      continueWorkflow: true,
      fallbackValue: '',
    },
  },
  try_catch: {
    type: 'try_catch',
    label: 'Try / Catch',
    category: 'logic',
    description: 'Catch errors from chosen nodes or try branch without stopping workflow',
    icon: 'ShieldAlert',
    reactFlowType: 'errorHandlerNode',
    defaultProperties: {
      watchMode: 'chosen',
      watchedNodeIds: [],
      action: 'catch_and_continue',
      outputVariable: 'lastError',
      continueWorkflow: true,
      fallbackValue: '',
    },
  },
  break: {
    type: 'break',
    label: 'Break',
    category: 'logic',
    description: 'Exit currently active loop',
    icon: 'Octagon',
    defaultProperties: {},
  },
  continue: {
    type: 'continue',
    label: 'Continue',
    category: 'logic',
    description: 'Skip to next loop iteration',
    icon: 'Play',
    defaultProperties: {},
  },

  // Data
  get_page_info: {
    type: 'get_page_info',
    label: 'Get Page Info',
    category: 'data',
    description: 'Capture active tab URL, page title, domain, meta tags, and document status',
    icon: 'Compass',
    defaultProperties: {
      includeMeta: true,
      unpackVariables: true,
      outputVariable: 'pageInfo',
    },
  },
  get_url_details: {
    type: 'get_url_details',
    label: 'URL Details & Params',
    category: 'data',
    description: 'Parse URL components, paths, protocol, and extract query string parameters',
    icon: 'Link2',
    defaultProperties: {
      sourceUrl: 'current',
      targetParam: '',
      outputVariable: 'urlDetails',
    },
  },
  date_time: {
    type: 'date_time',
    label: 'Date & Time',
    category: 'data',
    description: 'Generate timestamps, format dates, calculate date differences, or apply offsets',
    icon: 'Calendar',
    defaultProperties: {
      mode: 'current_time',
      inputDate: '',
      format: 'iso',
      customFormat: 'YYYY-MM-DD HH:mm:ss',
      timeZone: 'local',
      amount: 1,
      unit: 'days',
      compareDate: '',
      outputVariable: 'dateTimeResult',
    },
  },
  cookie_manager: {
    type: 'cookie_manager',
    label: 'Cookie Manager',
    category: 'data',
    description: 'Inspect, retrieve, set, or delete browser cookies for session handling',
    icon: 'Cookie',
    defaultProperties: {
      action: 'get',
      url: '',
      name: '',
      value: '',
      domain: '',
      path: '/',
      secure: true,
      sameSite: 'lax',
      outputVariable: 'cookieResult',
    },
  },
  array_operation: {
    type: 'array_operation',
    label: 'Array Utilities',
    category: 'data',
    description: 'Filter, sort, deduplicate, slice, push, or join arrays without custom scripts',
    icon: 'ListOrdered',
    defaultProperties: {
      array: '{{items}}',
      operation: 'deduplicate',
      item: '',
      field: '',
      filterOperator: 'not_empty',
      filterValue: '',
      sliceStart: 0,
      sliceEnd: 10,
      sortOrder: 'asc',
      delimiter: ', ',
      outputVariable: 'processedArray',
    },
  },
  string_template: {
    type: 'string_template',
    label: 'String Template',
    category: 'data',
    description: 'Build formatted multi-line text, markdown, or messages with variable interpolation',
    icon: 'FileCode',
    defaultProperties: {
      template: 'Hello {{name}},\nYour status is {{status}}.',
      casing: 'none',
      escapeHtml: false,
      outputVariable: 'renderedTemplate',
    },
  },
  json_query: {
    type: 'json_query',
    label: 'JSON Query',
    category: 'data',
    description: 'Extract nested values or arrays from JSON objects using dot/bracket path queries',
    icon: 'Braces',
    defaultProperties: {
      jsonInput: '{{apiResponse}}',
      queryPath: 'data.items[0].id',
      fallbackValue: '',
      outputVariable: 'jsonQueryResult',
    },
  },
  set_variable: {
    type: 'set_variable',
    label: 'Set Variable',
    category: 'data',
    description: 'Assign a value or expression to a variable',
    icon: 'Variable',
    defaultProperties: {
      name: 'myVar',
      value: '',
    },
  },
  get_variable: {
    type: 'get_variable',
    label: 'Get Variable',
    category: 'data',
    description: 'Retrieve stored variable',
    icon: 'Eye',
    defaultProperties: {
      name: '',
    },
  },
  transform: {
    type: 'transform',
    label: 'Transform',
    category: 'data',
    description: 'Transform text, format casing, or parse data',
    icon: 'Sparkles',
    defaultProperties: {
      input: '',
      operation: 'trim',
      field: '',
      outputVariable: 'transformedText',
    },
  },
  regex: {
    type: 'regex',
    label: 'Regex',
    category: 'data',
    description: 'Extract matches using regular expression',
    icon: 'Regex',
    defaultProperties: {
      text: '',
      pattern: '',
      flags: 'g',
      outputVariable: 'regexMatches',
    },
  },
  json_parse: {
    type: 'json_parse',
    label: 'JSON Parse',
    category: 'data',
    description: 'Parse JSON string into an object or array',
    icon: 'FileJson',
    defaultProperties: {
      text: '',
      outputVariable: 'parsedJson',
    },
  },
  generate_data: {
    type: 'generate_data',
    label: 'Generate Data',
    category: 'data',
    description: 'Generate mock random data (email, name, UUID, timestamp)',
    icon: 'Sparkles',
    defaultProperties: {
      dataType: 'email',
      outputVariable: 'generatedData',
    },
  },
  math_calculate: {
    type: 'math_calculate',
    label: 'Math & Counter',
    category: 'data',
    description: 'Perform arithmetic operations, increment counters, or evaluate math expressions with live value display',
    icon: 'Calculator',
    defaultProperties: {
      operation: 'add', // 'add' | 'subtract' | 'multiply' | 'divide' | 'increment' | 'decrement' | 'formula'
      leftOperand: '{{counter}}',
      rightOperand: '1',
      formula: '',
      outputVariable: 'counter',
    },
  },
  export_data: {
    type: 'export_data',
    label: 'Export Data (CSV/XLSX/JSON)',
    category: 'data',
    description: 'Format and export collected data, multiple variables, or webpage elements directly into CSV, Excel (.xlsx), JSON, or TSV with auto-download',
    icon: 'FileSpreadsheet',
    defaultProperties: {
      format: 'csv', // 'csv' | 'xlsx' | 'json' | 'tsv' | 'html_table'
      sourceMode: 'variable', // 'variable' | 'multiple_variables' | 'dom_elements' | 'custom_json'
      datasetVariable: 'extractedList',
      columns: [
        { header: 'Title', value: '{{titles}}' },
        { header: 'Price', value: '{{prices}}' },
      ],
      domContainerSelector: '',
      domFields: [
        { name: 'title', selector: '', attribute: '' },
        { name: 'link', selector: 'a', attribute: 'href' },
      ],
      customJson: '[{"name": "{{name}}", "value": "{{val}}"}]',
      filename: 'collected_data',
      autoDownload: true,
      saveAs: false,
      copyToClipboard: false,
      csvDelimiter: ',',
      includeHeaders: true,
      excludeEmpty: false,
      filterEmptyMode: 'any',
      sheetName: 'Data',
      outputVariable: 'exportedData',
    },
  },
  combine_datasets: {
    type: 'combine_datasets',
    label: 'Combine Datasets',
    category: 'data',
    description: 'Combine multiple schemas and product scrapes with alignment, column mapping, and deduplication',
    icon: 'Layers',
    reactFlowType: 'combineDatasetsNode',
    defaultProperties: {
      sourceMode: 'incoming_edges', // 'incoming_edges' | 'variables'
      sourceVariables: ['scrapedProducts1', 'scrapedProducts2'],
      mode: 'union', // 'union' | 'intersection' | 'key_join'
      missingValue: '',
      addSourceColumn: true,
      sourceColumnName: '_source',
      columnMappings: [],
      deduplicate: true,
      dedupKeys: [],
      dedupStrategy: 'merge_coalesce', // 'keep_first' | 'keep_last' | 'merge_coalesce' | 'highest_completeness'
      caseSensitive: false,
      normalizeUrls: true,
      primaryKey: 'title',
      outputVariable: 'combinedDataset',
    },
  },
  generate_pdf: {
    type: 'generate_pdf',
    label: 'Generate PDF Document',
    category: 'data',
    description: 'Generate professional executive PDFs with 6 visual themes, full Markdown support, image injection, and AI content synthesis',
    icon: 'FileText',
    defaultProperties: {
      title: 'Executive Scrape Briefing',
      subtitle: 'Multi-Source Product & Market Intelligence',
      author: 'AutoFlow AI',
      theme: 'modern_clean', // 'modern_clean' | 'executive_dark' | 'minimalist_light' | 'corporate_blue' | 'academic_formal' | 'cyber_tech'
      useAi: false,
      aiPrompt: 'Summarize the extracted items in {{combinedDataset}} into a structured executive report with key findings table and strategic insights.',
      aiModel: 'gpt-5.6-sol',
      contentMarkdown: '# Executive Summary\n\nGenerated intelligence report based on extracted dataset.\n\n| Item | Status |\n| --- | --- |\n| Analysis | Completed |',
      pageSize: 'A4', // 'A4' | 'Letter'
      orientation: 'portrait', // 'portrait' | 'landscape'
      headerText: 'AutoFlow Briefing',
      footerText: 'AutoFlow Browser Automation',
      includePageNumbers: true,
      includeTimestamp: true,
      coverPage: false,
      images: [], // [{ url: '{{screenshotUrl}}', placement: 'cover_page', caption: 'Live View' }]
      autoDownload: true,
      filename: 'autoflow_report.pdf',
      saveToStorage: false,
      storageKey: 'report_pdf',
      outputVariable: 'generatedPdf',
    },
  },
  simple_storage: {
    type: 'simple_storage',
    label: 'Simple Storage',
    category: 'data',
    description: 'Universal shared data store for Arrays, Dictionaries, Primitive Variables, Images, and Documents accessible by any node',
    icon: 'Archive',
    reactFlowType: 'simpleStorageNode',
    defaultProperties: {
      action: 'set', // 'set' | 'get' | 'append' | 'merge' | 'delete' | 'clear' | 'list'
      key: 'myItems',
      entryType: 'array', // 'array' | 'dictionary' | 'variable' | 'image' | 'document'
      value: '[]',
      scope: 'workflow', // 'workflow' | 'persistent'
      deepMerge: true,
      outputVariable: 'storageResult',
    },
  },
  dataset_input: {
    type: 'dataset_input',
    label: 'Dataset / File Input',
    category: 'data',
    description: 'Import CSV, TSV, or JSON dataset, preview rows, and expose items for looping or downstream nodes',
    icon: 'FileSpreadsheet',
    reactFlowType: 'datasetInputNode',
    defaultProperties: {
      sourceType: 'file', // 'file' | 'paste'
      importedItems: [],
      importedHeaders: [],
      importedFilename: '',
      rawContent: '',
      outputVariable: 'dataset',
    },
  },
  print: {
    type: 'print',
    label: 'Print',
    category: 'data',
    description: 'Print variables, arrays, objects, or text messages directly to console and execution logs',
    icon: 'Printer',
    defaultProperties: {
      message: '{{result}}',
      format: 'auto', // 'auto' | 'json' | 'table' | 'text'
      toConsole: true,
      outputVariable: '',
    },
  },

  // Utility
  screenshot: {
    type: 'screenshot',
    label: 'Screenshot',
    category: 'utility',
    description: 'Capture screenshot of current page or viewport with live canvas thumbnail preview',
    icon: 'Camera',
    defaultProperties: {
      outputVariable: 'screenshotUrl',
    },
  },
  execute_javascript: {
    type: 'execute_javascript',
    label: 'Execute JS',
    category: 'utility',
    description: 'Run custom JavaScript script in page context',
    icon: 'Terminal',
    defaultProperties: {
      code: 'return document.title;',
      outputVariable: 'scriptResult',
    },
  },
  http_request: {
    type: 'http_request',
    label: 'HTTP Request',
    category: 'utility',
    description: 'Make an API request (GET, POST, etc.) with real-time status display',
    icon: 'Send',
    defaultProperties: {
      method: 'GET',
      url: 'https://httpbin.org/get',
      outputVariable: 'apiResponse',
    },
  },
  storage_manage: {
    type: 'storage_manage',
    label: 'Storage Manage',
    category: 'utility',
    description: 'Get, set, or clear localStorage and sessionStorage',
    icon: 'Database',
    defaultProperties: {
      type: 'local',
      action: 'get',
      key: '',
      value: '',
      outputVariable: 'storedValue',
    },
  },
  clipboard: {
    type: 'clipboard',
    label: 'Clipboard',
    category: 'utility',
    description: 'Copy text to or read text from system clipboard',
    icon: 'Clipboard',
    defaultProperties: {
      action: 'write',
      text: '{{extractedData}}',
      outputVariable: 'clipboardText',
    },
  },
  download_file: {
    type: 'download_file',
    label: 'Download File',
    category: 'utility',
    description: 'Download file, image, data URL, or CSV/JSON content to disk with live progress feedback',
    icon: 'Download',
    defaultProperties: {
      sourceType: 'variable', // 'variable' | 'url' | 'content'
      url: '{{screenshotUrl}}',
      content: '',
      filename: 'downloaded_file.png',
      saveAs: false,
      outputVariable: 'downloadResult',
    },
  },
  show_notification: {
    type: 'show_notification',
    label: 'Desktop Notification',
    category: 'utility',
    description: 'Trigger an interactive desktop alert notification with sound and title',
    icon: 'Bell',
    defaultProperties: {
      title: 'AutoFlow Alert',
      message: 'Workflow reached this step successfully!',
      iconUrl: '',
      requireInteraction: false,
      outputVariable: 'notificationResult',
    },
  },
  ai_agent: {
    type: 'ai_agent',
    label: 'AI Agent',
    category: 'utility',
    description: 'Run LLM prompt to summarize, classify, or analyze page data',
    icon: 'Brain',
    defaultProperties: {
      prompt: 'Summarize the extracted content: {{extractedText}}',
      model: 'gpt-5.6-sol',
      outputVariable: 'aiAnalysis',
      jsonMode: false,
      outputFormat: 'text', // 'text' | 'json' | 'csv' | 'xlsx' | 'pdf'
      autoDownload: false,
      downloadFilename: 'ai_report',
    },
  },
  autonomous_agent: {
    type: 'autonomous_agent',
    label: 'Autonomous Agent',
    category: 'utility',
    description: 'Vision-driven AI agent that clicks, types, and navigates based on a goal',
    icon: 'Bot',
    defaultProperties: {
      goal: 'Find {{query}} on page and extract details',
      maxSteps: 10,
      model: 'gpt-5.6-sol',
      outputVariable: 'agentResult',
    },
  },
  generate_image: {
    type: 'generate_image',
    label: 'AI Image Generator',
    category: 'utility',
    description: 'Generate images using OpenAI DALL-E, GMI Cloud Hunyuan Image 3.5, or custom models with separate API key & base URL',
    icon: 'ImagePlus',
    defaultProperties: {
      prompt: 'A futuristic digital illustration of {{pageTitle}}',
      inputImage: '', // Optional Image URL, base64 data URI, or {{variable}} for img2img / reference
      asyncCount: 1, // 1 | 2 | 4 | 8 (asynchronous generation count)
      model: 'dall-e-3', // 'dall-e-3' | 'dall-e-2' | 'hy-image-v3.5-preview' | 'custom'
      size: '1024x1024',
      quality: 'standard',
      style: 'vivid',
      responseFormat: 'url',
      apiKey: '',
      baseUrl: '',
      outputVariable: 'generatedImageUrl',
      autoDownload: false,
      downloadFilename: 'generated_image',
    },
  },

  // Messaging & Notifications
  telegram_message: {
    type: 'telegram_message',
    label: 'Telegram Message',
    category: 'messaging',
    description: 'Send messages, photos, screenshots, or alerts to Telegram via Bot API',
    icon: 'Send',
    defaultProperties: {
      credentialId: '',
      botToken: '',
      chatId: '',
      messageType: 'text', // 'text' | 'photo' | 'document'
      message: 'AutoFlow notification: {{extractedText}}',
      imageUrl: '', // Can be image URL, data URL, or {{screenshotUrl}}
      caption: '',
      parseMode: 'HTML',
      silent: false,
      protectContent: false,
      outputVariable: 'telegramResponse',
    },
  },
  telegram_watch: {
    type: 'telegram_watch',
    label: 'Watch Telegram Updates',
    category: 'messaging',
    description: 'Wait for incoming Telegram messages and extract chat ID, message text, and user variables',
    icon: 'Radio',
    defaultProperties: {
      credentialId: '',
      botToken: '',
      allowedChatId: '',
      timeoutSeconds: 60,
      unlimitedTimeout: false,
      recurring: false,
      maxIterations: 0,
      delayBetweenMs: 1000,
      pollIntervalMs: 2000,
      markAsRead: true,
      onlyNewMessages: true,
      textVariable: 'telegramMessage',
      chatIdVariable: 'telegramChatId',
      senderUsernameVariable: 'telegramUsername',
      senderNameVariable: 'telegramSenderName',
      rawUpdateVariable: 'telegramUpdate',
      outputVariable: 'telegramMessage',
    },
  },
  discord_message: {
    type: 'discord_message',
    label: 'Discord Message',
    category: 'messaging',
    description: 'Send alerts, rich embeds, images, and screenshots to Discord',
    icon: 'MessageSquare',
    defaultProperties: {
      credentialId: '',
      mode: 'webhook',
      webhookUrl: '',
      botToken: '',
      channelId: '',
      messageType: 'text', // 'text' | 'embed' | 'image'
      content: 'AutoFlow notification: {{extractedText}}',
      imageUrl: '', // Image URL, base64 data URL, or {{screenshotUrl}}
      username: 'AutoFlow Bot',
      avatarUrl: '',
      embedTitle: '',
      embedDescription: '',
      embedColor: '#5865F2',
      embedFooter: '',
      embedThumbnail: '',
      embedFields: [], // [{ name: 'Status', value: 'OK', inline: true }]
      outputVariable: 'discordResponse',
    },
  },
  discord_watch: {
    type: 'discord_watch',
    label: 'Watch Discord Updates',
    category: 'messaging',
    description: 'Listen for new messages in a Discord channel and extract author, text, and variables',
    icon: 'Radio',
    defaultProperties: {
      credentialId: '',
      botToken: '',
      channelId: '',
      allowedUserId: '',
      ignoreBots: true,
      timeoutSeconds: 60,
      unlimitedTimeout: false,
      recurring: false,
      maxIterations: 0,
      delayBetweenMs: 1000,
      pollIntervalMs: 2000,
      onlyNewMessages: true,
      textVariable: 'discordMessage',
      authorVariable: 'discordUsername',
      senderNameVariable: 'discordSenderName',
      authorIdVariable: 'discordAuthorId',
      channelIdVariable: 'discordChannelId',
      attachmentUrlVariable: 'discordAttachmentUrl',
      rawUpdateVariable: 'discordUpdate',
      outputVariable: 'discordMessage',
    },
  },
  slack_message: {
    type: 'slack_message',
    label: 'Slack Message',
    category: 'messaging',
    description: 'Post messages, rich Block Kit cards, images, or screenshots to Slack',
    icon: 'Hash',
    defaultProperties: {
      credentialId: '',
      mode: 'webhook',
      webhookUrl: '',
      botToken: '',
      channel: '#general',
      messageType: 'text', // 'text' | 'rich' | 'image'
      text: 'AutoFlow notification: {{extractedText}}',
      headerText: '',
      imageUrl: '', // Image URL, base64 data URL, or {{screenshotUrl}}
      imageAlt: 'AutoFlow Image',
      fields: [], // [{ label: 'Price', value: '{{price}}' }]
      footerText: '',
      username: 'AutoFlow Bot',
      iconEmoji: ':robot_face:',
      outputVariable: 'slackResponse',
    },
  },
  slack_watch: {
    type: 'slack_watch',
    label: 'Watch Slack Updates',
    category: 'messaging',
    description: 'Listen for new messages in a Slack channel and extract sender, text, and variables',
    icon: 'Radio',
    defaultProperties: {
      credentialId: '',
      botToken: '',
      channel: '#general',
      allowedUserId: '',
      ignoreBots: true,
      timeoutSeconds: 60,
      unlimitedTimeout: false,
      recurring: false,
      maxIterations: 0,
      delayBetweenMs: 1000,
      pollIntervalMs: 2000,
      onlyNewMessages: true,
      textVariable: 'slackMessage',
      userIdVariable: 'slackUserId',
      channelVariable: 'slackChannel',
      timestampVariable: 'slackTimestamp',
      rawUpdateVariable: 'slackUpdate',
      outputVariable: 'slackMessage',
    },
  },

  // Commands & Workflow Control
  stop_timer: {
    type: 'stop_timer',
    label: 'Stop Timer',
    category: 'command',
    description: 'Stop or cancel running wait timer(s) when a condition matches',
    icon: 'TimerOff',
    defaultProperties: {
      targetTimer: 'all',
      action: 'complete_early',
      reason: 'Condition matched',
      outputVariable: 'timerStopped',
    },
  },
  reset_timer: {
    type: 'reset_timer',
    label: 'Reset Timer',
    category: 'command',
    description: 'Restart or extend the duration of an active wait timer',
    icon: 'RotateCcw',
    defaultProperties: {
      targetTimer: 'all',
      mode: 'restart',
      extendMs: 5000,
      outputVariable: 'timerReset',
    },
  },
  stop_workflow: {
    type: 'stop_workflow',
    label: 'Stop Workflow',
    category: 'command',
    description: 'Terminate workflow execution cleanly (successful early exit or stop)',
    icon: 'StopCircle',
    defaultProperties: {
      exitStatus: 'completed',
      exitMessage: 'Workflow stopped early by command',
      saveOutput: true,
    },
  },
  pause_workflow: {
    type: 'pause_workflow',
    label: 'Pause Workflow',
    category: 'command',
    description: 'Pause execution for manual user review or captcha solving before continuing',
    icon: 'PauseCircle',
    defaultProperties: {
      message: 'Workflow paused. Click Resume to continue.',
      autoResumeMs: 0,
    },
  },
  skip_to: {
    type: 'skip_to',
    label: 'Skip to Node',
    category: 'command',
    description: 'Skip intermediate steps and jump execution directly to a target node',
    icon: 'FastForward',
    defaultProperties: {
      targetNodeId: '',
      reason: 'Skipped to target node',
    },
  },
};

export const CATEGORIES: { id: NodeCategory; label: string; color: string }[] = [
  { id: 'browser', label: 'Browser', color: '#3b82f6' },
  { id: 'interaction', label: 'Interaction', color: '#6366f1' },
  { id: 'wait', label: 'Wait', color: '#f59e0b' },
  { id: 'extraction', label: 'Extraction', color: '#10b981' },
  { id: 'scrapers', label: 'Scrapers', color: '#f97316' },
  { id: 'logic', label: 'Logic', color: '#8b5cf6' },
  { id: 'data', label: 'Data', color: '#ec4899' },
  { id: 'utility', label: 'Utility', color: '#06b6d4' },
  { id: 'messaging', label: 'Messaging', color: '#14b8a6' },
  { id: 'command', label: 'Commands', color: '#f43f5e' },
];

export function getNodeDefinition(type: NodeType): NodeDefinition {
  return NODE_REGISTRY[type] || NODE_REGISTRY.navigate;
}
