import { NodeType, NodeCategory } from '../types/workflow';

export interface NodeDefinition {
  type: NodeType;
  label: string;
  category: NodeCategory;
  description: string;
  icon: string; // Lucide icon name
  defaultProperties: Record<string, any>;
  reactFlowType?: string; // 'customNode' | 'conditionNode' | 'loopNode'
}

export const NODE_REGISTRY: Record<NodeType, NodeDefinition> = {
  // Browser
  navigate: {
    type: 'navigate',
    label: 'Navigate',
    category: 'browser',
    description: 'Go to a web page URL',
    icon: 'Globe',
    defaultProperties: {
      url: 'https://example.com',
      waitUntil: 'load',
      openInNewTab: false,
      timeout: 30000,
    },
  },
  back: {
    type: 'back',
    label: 'Back',
    category: 'browser',
    description: 'Navigate backward in history',
    icon: 'ArrowLeft',
    defaultProperties: {},
  },
  forward: {
    type: 'forward',
    label: 'Forward',
    category: 'browser',
    description: 'Navigate forward in history',
    icon: 'ArrowRight',
    defaultProperties: {},
  },
  reload: {
    type: 'reload',
    label: 'Reload',
    category: 'browser',
    description: 'Reload the current page',
    icon: 'RotateCw',
    defaultProperties: {},
  },
  new_tab: {
    type: 'new_tab',
    label: 'New Tab',
    category: 'browser',
    description: 'Open a new browser tab',
    icon: 'PlusSquare',
    defaultProperties: {
      url: 'about:blank',
    },
  },
  close_tab: {
    type: 'close_tab',
    label: 'Close Tab',
    category: 'browser',
    description: 'Close the current or target tab',
    icon: 'XSquare',
    defaultProperties: {
      closeTarget: 'current',
      tabIndex: 0,
      urlPattern: '',
    },
  },
  switch_tab: {
    type: 'switch_tab',
    label: 'Switch Tab',
    category: 'browser',
    description: 'Switch active browser tab',
    icon: 'Layers',
    defaultProperties: {
      tabTarget: 'next',
      tabIndex: 0,
      urlPattern: '',
      titlePattern: '',
    },
  },

  // Interaction
  click: {
    type: 'click',
    label: 'Click',
    category: 'interaction',
    description: 'Click an element on the webpage',
    icon: 'MousePointer',
    defaultProperties: {
      selector: '',
      clickType: 'left',
      timeout: 10000,
    },
  },
  type_text: {
    type: 'type_text',
    label: 'Type Text',
    category: 'interaction',
    description: 'Type text or variables into an input field',
    icon: 'Type',
    defaultProperties: {
      selector: '',
      text: '',
      clearExisting: true,
      typingDelay: 0,
      timeout: 10000,
    },
  },
  clear_input: {
    type: 'clear_input',
    label: 'Clear Input',
    category: 'interaction',
    description: 'Clear the contents of an input element',
    icon: 'Delete',
    defaultProperties: {
      selector: '',
      timeout: 10000,
    },
  },
  hover: {
    type: 'hover',
    label: 'Hover',
    category: 'interaction',
    description: 'Hover mouse cursor over an element',
    icon: 'Pointer',
    defaultProperties: {
      selector: '',
      timeout: 10000,
    },
  },
  press_key: {
    type: 'press_key',
    label: 'Press Key',
    category: 'interaction',
    description: 'Simulate pressing a keyboard key (e.g. Enter)',
    icon: 'Keyboard',
    defaultProperties: {
      key: 'Enter',
      selector: '',
    },
  },
  scroll: {
    type: 'scroll',
    label: 'Scroll',
    category: 'interaction',
    description: 'Scroll the page or a container element',
    icon: 'ChevronsDown',
    defaultProperties: {
      direction: 'down',
      amount: 400,
      smooth: true,
    },
  },
  smart_scroll: {
    type: 'smart_scroll',
    label: 'Smart Scroll',
    category: 'interaction',
    description: 'Smoothly scroll until bottom, element appears, or N iterations with live step progress',
    icon: 'ChevronsDown',
    defaultProperties: {
      mode: 'to_bottom', // 'to_bottom' | 'to_element' | 'distance'
      selector: '',
      distance: 600,
      maxScrolls: 5,
      scrollSpeed: 'normal', // 'slow' | 'normal' | 'fast' | 'instant' | 'custom'
      scrollDelay: 800,
      outputVariable: 'scrollResult',
    },
  },
  select_dropdown: {
    type: 'select_dropdown',
    label: 'Select Dropdown',
    category: 'interaction',
    description: 'Choose an option in a select dropdown',
    icon: 'ListFilter',
    defaultProperties: {
      selector: '',
      selectionType: 'value',
      value: '',
    },
  },
  drag_and_drop: {
    type: 'drag_and_drop',
    label: 'Drag & Drop',
    category: 'interaction',
    description: 'Drag element to another element target',
    icon: 'Move',
    defaultProperties: {
      sourceSelector: '',
      targetSelector: '',
    },
  },

  // Wait
  wait: {
    type: 'wait',
    label: 'Wait',
    category: 'wait',
    description: 'Pause execution for specified duration',
    icon: 'Clock',
    defaultProperties: {
      duration: 2000,
      timeout: 2000,
      unit: 'ms',
      timerName: '',
      stopCondition: {
        enabled: false,
        type: 'text',
        text: '',
        matchMode: 'partial',
        caseSensitive: false,
        selector: '',
        operator: 'equals',
        leftValue: '',
        rightValue: '',
      },
    },
  },
  wait_for_element: {
    type: 'wait_for_element',
    label: 'Wait For Element',
    category: 'wait',
    description: 'Wait until element appears and is visible',
    icon: 'Search',
    defaultProperties: {
      selector: '',
      timeout: 10000,
      visible: true,
      enabled: false,
    },
  },
  wait_for_text: {
    type: 'wait_for_text',
    label: 'Wait For Text',
    category: 'wait',
    description: 'Wait until specific text appears on the page',
    icon: 'FileText',
    defaultProperties: {
      text: '',
      selector: '',
      timeout: 10000,
      matchMode: 'partial',
      caseSensitive: false,
    },
  },
  wait_for_navigation: {
    type: 'wait_for_navigation',
    label: 'Wait For Navigation',
    category: 'wait',
    description: 'Wait for page URL change or navigation to complete',
    icon: 'Compass',
    defaultProperties: {
      urlPattern: '',
      timeout: 15000,
    },
  },

  // Extraction
  extract_text: {
    type: 'extract_text',
    label: 'Extract Text',
    category: 'extraction',
    description: 'Extract text content from an element',
    icon: 'FileText',
    defaultProperties: {
      selector: '',
      outputVariable: 'extractedText',
      timeout: 10000,
    },
  },
  extract_attribute: {
    type: 'extract_attribute',
    label: 'Extract Attribute',
    category: 'extraction',
    description: 'Extract an attribute like href, src, or value',
    icon: 'Tag',
    defaultProperties: {
      selector: '',
      attribute: 'href',
      outputVariable: 'extractedAttr',
      timeout: 10000,
    },
  },
  extract_html: {
    type: 'extract_html',
    label: 'Extract HTML',
    category: 'extraction',
    description: 'Extract outer or inner HTML from an element',
    icon: 'Code',
    defaultProperties: {
      selector: '',
      mode: 'outer',
      outputVariable: 'extractedHtml',
    },
  },
  extract_table: {
    type: 'extract_table',
    label: 'Extract Table',
    category: 'extraction',
    description: 'Parse HTML table into structured JSON rows',
    icon: 'Table',
    defaultProperties: {
      selector: 'table',
      outputVariable: 'tableData',
    },
  },
  extract_multiple: {
    type: 'extract_multiple',
    label: 'Extract Multiple Elements',
    category: 'extraction',
    description: 'Extract text or attributes from all matching elements into an array with inline loop body',
    icon: 'ListChecks',
    reactFlowType: 'iteratorNode',
    defaultProperties: {
      selector: '',
      attribute: '',
      itemVariable: 'currentElement',
      outputVariable: 'extractedList',
      timeout: 10000,
      exportToFile: false,
      exportFormat: 'csv', // 'csv' | 'xlsx' | 'json' | 'tsv'
      exportFilename: 'extracted_items',
    },
  },
  crawl_pagination: {
    type: 'crawl_pagination',
    label: 'Auto-Crawler (Pagination)',
    category: 'extraction',
    description: 'Crawls N pages via Next button or infinite scroll, appending rows into a single dataset',
    icon: 'Layers',
    reactFlowType: 'iteratorNode',
    defaultProperties: {
      mode: 'auto_detect',
      itemSelector: '',
      nextButtonSelector: '',
      attribute: '',
      maxPages: 5,
      pageDelay: 1500,
      stopOnNoNewItems: true,
      deduplicate: true,
      itemVariable: 'crawledItem',
      outputVariable: 'crawledDataset',
      totalExtractedVariable: 'totalCrawledItems',
      exportToFile: false,
      exportFormat: 'csv', // 'csv' | 'xlsx' | 'json' | 'tsv'
      exportFilename: 'crawled_dataset',
    },
  },
  extract_links: {
    type: 'extract_links',
    label: 'Extract Links',
    category: 'extraction',
    description: 'Scrape all hyperlinks with their text and URLs',
    icon: 'Link',
    defaultProperties: {
      selector: '',
      outputVariable: 'extractedLinks',
      timeout: 10000,
    },
  },
  extract_image: {
    type: 'extract_image',
    label: 'Extract Image',
    category: 'extraction',
    description: 'Extract image URL or base64 data from an element, background, or page',
    icon: 'Image',
    reactFlowType: 'iteratorNode',
    defaultProperties: {
      selector: 'img',
      mode: 'single', // 'single' | 'multiple'
      asBase64: false,
      includeBackground: true,
      itemVariable: 'currentImage',
      outputVariable: 'extractedImage',
      timeout: 10000,
    },
  },
  extract_all_images: {
    type: 'extract_all_images',
    label: 'Find All Images',
    category: 'extraction',
    description: 'Find and extract all images from the page or container with inline loop body',
    icon: 'Images',
    reactFlowType: 'iteratorNode',
    defaultProperties: {
      containerSelector: '',
      includeBackground: true,
      asBase64: false,
      minWidth: 10,
      minHeight: 10,
      maxImages: 100,
      itemVariable: 'currentImage',
      outputVariable: 'allImages',
      timeout: 10000,
    },
  },
  scrape_elements: {
    type: 'scrape_elements',
    label: 'Scrape Elements (Product Cards)',
    category: 'extraction',
    description: 'Extract structured multi-field cards (title, price, image, link, paragraphs) from repeating elements with loop body and file export',
    icon: 'LayoutGrid',
    reactFlowType: 'iteratorNode',
    defaultProperties: {
      containerSelector: '.product-card',
      fields: [
        { name: 'title', selector: 'h2, h3, h4, .title, [class*="title"]', attribute: 'text' },
        { name: 'price', selector: '.price, [class*="price"]', attribute: 'text' },
        { name: 'image', selector: 'img', attribute: 'src' },
        { name: 'link', selector: 'a', attribute: 'href' },
        { name: 'description', selector: 'p', attribute: 'paragraphs' },
      ],
      itemVariable: 'currentProduct',
      itemExtractField: 'all', // 'all' (whole card object) | 'link' | 'title' | 'price' | 'image' | 'description' | custom field
      itemExtractCustomField: '',
      outputVariable: 'scrapedProducts',
      exportToFile: false,
      exportFormat: 'csv',
      exportFilename: 'scraped_products',
      excludeEmpty: false,
      filterEmptyMode: 'any',
      // Post-Processing & Normalization
      postProcessingEnabled: false,
      urlBasePrefix: '',
      urlTargetFields: ['link'],
      stripUrlQueryParams: false,
      stripAllQueryParams: false,
      cleanPrice: false,
      priceMode: 'number_only', // 'number_only' | 'strip_symbols'
      formatDate: false,
      dateMode: 'iso_date', // 'iso_date' | 'iso_datetime' | 'timestamp'
      // Pattern Filter Condition ("if url in this pattern then only")
      patternFilterEnabled: false,
      patternFilterField: 'link',
      patternFilterAction: 'include_only', // 'include_only' | 'exclude_matching'
      patternFilterMode: 'contains', // 'contains' | 'regex' | 'starts_with' | 'ends_with'
      patternFilterValue: '',
      timeout: 10000,
    },
  },

  // Logic
  condition: {
    type: 'condition',
    label: 'Condition',
    category: 'logic',
    description: 'Branch workflow execution based on condition',
    icon: 'GitBranch',
    reactFlowType: 'conditionNode',
    defaultProperties: {
      leftValue: '',
      operator: 'equals',
      rightValue: '',
      caseSensitive: false,
    },
  },
  contains: {
    type: 'contains',
    label: 'Contains',
    category: 'logic',
    description: 'Check whether an element is present on the page (TRUE / FALSE branches)',
    icon: 'SearchCheck',
    reactFlowType: 'containsNode',
    defaultProperties: {
      selector: '',
      matchMode: 'element',
      text: '',
      textMatchMode: 'partial',
      caseSensitive: false,
      visibleOnly: true,
      timeout: 5000,
      outputVariable: 'elementPresent',
    },
  },
  contains_text: {
    type: 'contains_text',
    label: 'Contains Text',
    category: 'logic',
    description: 'Check whether a particular text exists on the page (TRUE / FALSE branches)',
    icon: 'FileText',
    reactFlowType: 'containsNode',
    defaultProperties: {
      text: '',
      selector: '',
      matchMode: 'partial',
      caseSensitive: false,
      timeout: 3000,
      outputVariable: 'containsText',
    },
  },
  and: {
    type: 'and',
    label: 'AND',
    category: 'logic',
    description: 'Combines multiple branches: requires ALL incoming branches to be TRUE / complete before proceeding',
    icon: 'GitMerge',
    reactFlowType: 'logicGateNode',
    defaultProperties: {
      gate: 'AND',
      outputVariable: 'andResult',
      mode: 'combine_branches',
    },
  },
  or: {
    type: 'or',
    label: 'OR',
    category: 'logic',
    description: 'Combines multiple branches: continues as soon as ANY incoming branch is TRUE / complete (race condition)',
    icon: 'GitFork',
    reactFlowType: 'logicGateNode',
    defaultProperties: {
      gate: 'OR',
      outputVariable: 'orResult',
      mode: 'combine_branches',
    },
  },
  nand: {
    type: 'nand',
    label: 'NAND',
    category: 'logic',
    description: 'Negated AND: Continues unless ALL incoming branches are TRUE',
    icon: 'Ban',
    reactFlowType: 'logicGateNode',
    defaultProperties: {
      gate: 'NAND',
      outputVariable: 'nandResult',
      mode: 'combine_branches',
    },
  },
  nor: {
    type: 'nor',
    label: 'NOR',
    category: 'logic',
    description: 'Negated OR: Continues only when ALL incoming branches are FALSE',
    icon: 'CircleSlash',
    reactFlowType: 'logicGateNode',
    defaultProperties: {
      gate: 'NOR',
      outputVariable: 'norResult',
      mode: 'combine_branches',
    },
  },
  logic_and: {
    type: 'logic_and',
    label: 'AND',
    category: 'logic',
    description: 'Combines multiple branches: requires ALL incoming branches to be TRUE / complete before proceeding',
    icon: 'GitMerge',
    reactFlowType: 'logicGateNode',
    defaultProperties: {
      gate: 'AND',
      outputVariable: 'andResult',
      mode: 'combine_branches',
    },
  },
  logic_or: {
    type: 'logic_or',
    label: 'OR',
    category: 'logic',
    description: 'Combines multiple branches: continues as soon as ANY incoming branch is TRUE / complete (race condition)',
    icon: 'GitFork',
    reactFlowType: 'logicGateNode',
    defaultProperties: {
      gate: 'OR',
      outputVariable: 'orResult',
      mode: 'combine_branches',
    },
  },
  logic_nand: {
    type: 'logic_nand',
    label: 'NAND',
    category: 'logic',
    description: 'Negated AND: Continues unless ALL incoming branches are TRUE',
    icon: 'Ban',
    reactFlowType: 'logicGateNode',
    defaultProperties: {
      gate: 'NAND',
      outputVariable: 'nandResult',
      mode: 'combine_branches',
    },
  },
  logic_nor: {
    type: 'logic_nor',
    label: 'NOR',
    category: 'logic',
    description: 'Negated OR: Continues only when ALL incoming branches are FALSE',
    icon: 'CircleSlash',
    reactFlowType: 'logicGateNode',
    defaultProperties: {
      gate: 'NOR',
      outputVariable: 'norResult',
      mode: 'combine_branches',
    },
  },
  loop: {
    type: 'loop',
    label: 'Loop',
    category: 'logic',
    description: 'Repeat connected downstream nodes N times',
    icon: 'Repeat',
    reactFlowType: 'loopNode',
    defaultProperties: {
      count: 3,
    },
  },
  for_each: {
    type: 'for_each',
    label: 'For Each',
    category: 'logic',
    description: 'Iterate through an array of items',
    icon: 'List',
    reactFlowType: 'loopNode',
    defaultProperties: {
      array: '{{items}}',
    },
  },
  try_catch: {
    type: 'try_catch',
    label: 'Try / Catch',
    category: 'logic',
    description: 'Catch errors and execute fallback action',
    icon: 'ShieldAlert',
    defaultProperties: {},
  },
  break: {
    type: 'break',
    label: 'Break',
    category: 'logic',
    description: 'Exit currently active loop',
    icon: 'Octagon',
    defaultProperties: {},
  },
  continue: {
    type: 'continue',
    label: 'Continue',
    category: 'logic',
    description: 'Skip to next loop iteration',
    icon: 'Play',
    defaultProperties: {},
  },

  // Data
  set_variable: {
    type: 'set_variable',
    label: 'Set Variable',
    category: 'data',
    description: 'Assign a value or expression to a variable',
    icon: 'Variable',
    defaultProperties: {
      name: 'myVar',
      value: '',
    },
  },
  get_variable: {
    type: 'get_variable',
    label: 'Get Variable',
    category: 'data',
    description: 'Retrieve stored variable',
    icon: 'Eye',
    defaultProperties: {
      name: '',
    },
  },
  transform: {
    type: 'transform',
    label: 'Transform',
    category: 'data',
    description: 'Transform text, format casing, or parse data',
    icon: 'Sparkles',
    defaultProperties: {
      input: '',
      operation: 'trim',
      field: '',
      outputVariable: 'transformedText',
    },
  },
  regex: {
    type: 'regex',
    label: 'Regex',
    category: 'data',
    description: 'Extract matches using regular expression',
    icon: 'Regex',
    defaultProperties: {
      text: '',
      pattern: '',
      flags: 'g',
      outputVariable: 'regexMatches',
    },
  },
  json_parse: {
    type: 'json_parse',
    label: 'JSON Parse',
    category: 'data',
    description: 'Parse JSON string into an object or array',
    icon: 'FileJson',
    defaultProperties: {
      text: '',
      outputVariable: 'parsedJson',
    },
  },
  generate_data: {
    type: 'generate_data',
    label: 'Generate Data',
    category: 'data',
    description: 'Generate mock random data (email, name, UUID, timestamp)',
    icon: 'Sparkles',
    defaultProperties: {
      dataType: 'email',
      outputVariable: 'generatedData',
    },
  },
  math_calculate: {
    type: 'math_calculate',
    label: 'Math & Counter',
    category: 'data',
    description: 'Perform arithmetic operations, increment counters, or evaluate math expressions with live value display',
    icon: 'Calculator',
    defaultProperties: {
      operation: 'add', // 'add' | 'subtract' | 'multiply' | 'divide' | 'increment' | 'decrement' | 'formula'
      leftOperand: '{{counter}}',
      rightOperand: '1',
      formula: '',
      outputVariable: 'counter',
    },
  },
  export_data: {
    type: 'export_data',
    label: 'Export Data (CSV/XLSX/JSON)',
    category: 'data',
    description: 'Format and export collected data, multiple variables, or webpage elements directly into CSV, Excel (.xlsx), JSON, or TSV with auto-download',
    icon: 'FileSpreadsheet',
    defaultProperties: {
      format: 'csv', // 'csv' | 'xlsx' | 'json' | 'tsv' | 'html_table'
      sourceMode: 'variable', // 'variable' | 'multiple_variables' | 'dom_elements' | 'custom_json'
      datasetVariable: 'extractedList',
      columns: [
        { header: 'Title', value: '{{titles}}' },
        { header: 'Price', value: '{{prices}}' },
      ],
      domContainerSelector: '',
      domFields: [
        { name: 'title', selector: '', attribute: '' },
        { name: 'link', selector: 'a', attribute: 'href' },
      ],
      customJson: '[{"name": "{{name}}", "value": "{{val}}"}]',
      filename: 'collected_data',
      autoDownload: true,
      saveAs: false,
      copyToClipboard: false,
      csvDelimiter: ',',
      includeHeaders: true,
      excludeEmpty: false,
      filterEmptyMode: 'any',
      sheetName: 'Data',
      outputVariable: 'exportedData',
    },
  },

  // Utility
  screenshot: {
    type: 'screenshot',
    label: 'Screenshot',
    category: 'utility',
    description: 'Capture screenshot of current page or viewport with live canvas thumbnail preview',
    icon: 'Camera',
    defaultProperties: {
      outputVariable: 'screenshotUrl',
    },
  },
  execute_javascript: {
    type: 'execute_javascript',
    label: 'Execute JS',
    category: 'utility',
    description: 'Run custom JavaScript script in page context',
    icon: 'Terminal',
    defaultProperties: {
      code: 'return document.title;',
      outputVariable: 'scriptResult',
    },
  },
  http_request: {
    type: 'http_request',
    label: 'HTTP Request',
    category: 'utility',
    description: 'Make an API request (GET, POST, etc.) with real-time status display',
    icon: 'Send',
    defaultProperties: {
      method: 'GET',
      url: 'https://httpbin.org/get',
      outputVariable: 'apiResponse',
    },
  },
  storage_manage: {
    type: 'storage_manage',
    label: 'Storage Manage',
    category: 'utility',
    description: 'Get, set, or clear localStorage and sessionStorage',
    icon: 'Database',
    defaultProperties: {
      type: 'local',
      action: 'get',
      key: '',
      value: '',
      outputVariable: 'storedValue',
    },
  },
  clipboard: {
    type: 'clipboard',
    label: 'Clipboard',
    category: 'utility',
    description: 'Copy text to or read text from system clipboard',
    icon: 'Clipboard',
    defaultProperties: {
      action: 'write',
      text: '{{extractedData}}',
      outputVariable: 'clipboardText',
    },
  },
  download_file: {
    type: 'download_file',
    label: 'Download File',
    category: 'utility',
    description: 'Download file, image, data URL, or CSV/JSON content to disk with live progress feedback',
    icon: 'Download',
    defaultProperties: {
      sourceType: 'variable', // 'variable' | 'url' | 'content'
      url: '{{screenshotUrl}}',
      content: '',
      filename: 'downloaded_file.png',
      saveAs: false,
      outputVariable: 'downloadResult',
    },
  },
  show_notification: {
    type: 'show_notification',
    label: 'Desktop Notification',
    category: 'utility',
    description: 'Trigger an interactive desktop alert notification with sound and title',
    icon: 'Bell',
    defaultProperties: {
      title: 'AutoFlow Alert',
      message: 'Workflow reached this step successfully!',
      iconUrl: '',
      requireInteraction: false,
      outputVariable: 'notificationResult',
    },
  },
  ai_agent: {
    type: 'ai_agent',
    label: 'AI Agent',
    category: 'utility',
    description: 'Run LLM prompt to summarize, classify, or analyze page data',
    icon: 'Brain',
    defaultProperties: {
      prompt: 'Summarize the extracted content: {{extractedText}}',
      model: 'gpt-5.6-sol',
      outputVariable: 'aiAnalysis',
      jsonMode: false,
      outputFormat: 'text', // 'text' | 'json' | 'csv' | 'xlsx' | 'pdf'
      autoDownload: false,
      downloadFilename: 'ai_report',
    },
  },
  autonomous_agent: {
    type: 'autonomous_agent',
    label: 'Autonomous Agent',
    category: 'utility',
    description: 'Vision-driven AI agent that clicks, types, and navigates based on a goal',
    icon: 'Bot',
    defaultProperties: {
      goal: 'Find {{query}} on page and extract details',
      maxSteps: 10,
      model: 'gpt-5.6-sol',
      outputVariable: 'agentResult',
    },
  },

  // Messaging & Notifications
  telegram_message: {
    type: 'telegram_message',
    label: 'Telegram Message',
    category: 'messaging',
    description: 'Send messages, photos, screenshots, or alerts to Telegram via Bot API',
    icon: 'Send',
    defaultProperties: {
      credentialId: '',
      botToken: '',
      chatId: '',
      messageType: 'text', // 'text' | 'photo' | 'document'
      message: 'AutoFlow notification: {{extractedText}}',
      imageUrl: '', // Can be image URL, data URL, or {{screenshotUrl}}
      caption: '',
      parseMode: 'HTML',
      silent: false,
      protectContent: false,
      outputVariable: 'telegramResponse',
    },
  },
  discord_message: {
    type: 'discord_message',
    label: 'Discord Message',
    category: 'messaging',
    description: 'Send alerts, rich embeds, images, and screenshots to Discord',
    icon: 'MessageSquare',
    defaultProperties: {
      credentialId: '',
      mode: 'webhook',
      webhookUrl: '',
      botToken: '',
      channelId: '',
      messageType: 'text', // 'text' | 'embed' | 'image'
      content: 'AutoFlow notification: {{extractedText}}',
      imageUrl: '', // Image URL, base64 data URL, or {{screenshotUrl}}
      username: 'AutoFlow Bot',
      avatarUrl: '',
      embedTitle: '',
      embedDescription: '',
      embedColor: '#5865F2',
      embedFooter: '',
      embedThumbnail: '',
      embedFields: [], // [{ name: 'Status', value: 'OK', inline: true }]
      outputVariable: 'discordResponse',
    },
  },
  slack_message: {
    type: 'slack_message',
    label: 'Slack Message',
    category: 'messaging',
    description: 'Post messages, rich Block Kit cards, images, or screenshots to Slack',
    icon: 'Hash',
    defaultProperties: {
      credentialId: '',
      mode: 'webhook',
      webhookUrl: '',
      botToken: '',
      channel: '#general',
      messageType: 'text', // 'text' | 'rich' | 'image'
      text: 'AutoFlow notification: {{extractedText}}',
      headerText: '',
      imageUrl: '', // Image URL, base64 data URL, or {{screenshotUrl}}
      imageAlt: 'AutoFlow Image',
      fields: [], // [{ label: 'Price', value: '{{price}}' }]
      footerText: '',
      username: 'AutoFlow Bot',
      iconEmoji: ':robot_face:',
      outputVariable: 'slackResponse',
    },
  },

  // Commands & Workflow Control
  stop_timer: {
    type: 'stop_timer',
    label: 'Stop Timer',
    category: 'command',
    description: 'Stop or cancel running wait timer(s) when a condition matches',
    icon: 'TimerOff',
    defaultProperties: {
      targetTimer: 'all',
      action: 'complete_early',
      reason: 'Condition matched',
      outputVariable: 'timerStopped',
    },
  },
  reset_timer: {
    type: 'reset_timer',
    label: 'Reset Timer',
    category: 'command',
    description: 'Restart or extend the duration of an active wait timer',
    icon: 'RotateCcw',
    defaultProperties: {
      targetTimer: 'all',
      mode: 'restart',
      extendMs: 5000,
      outputVariable: 'timerReset',
    },
  },
  stop_workflow: {
    type: 'stop_workflow',
    label: 'Stop Workflow',
    category: 'command',
    description: 'Terminate workflow execution cleanly (successful early exit or stop)',
    icon: 'StopCircle',
    defaultProperties: {
      exitStatus: 'completed',
      exitMessage: 'Workflow stopped early by command',
      saveOutput: true,
    },
  },
  pause_workflow: {
    type: 'pause_workflow',
    label: 'Pause Workflow',
    category: 'command',
    description: 'Pause execution for manual user review or captcha solving before continuing',
    icon: 'PauseCircle',
    defaultProperties: {
      message: 'Workflow paused. Click Resume to continue.',
      autoResumeMs: 0,
    },
  },
  skip_to: {
    type: 'skip_to',
    label: 'Skip to Node',
    category: 'command',
    description: 'Skip intermediate steps and jump execution directly to a target node',
    icon: 'FastForward',
    defaultProperties: {
      targetNodeId: '',
      reason: 'Skipped to target node',
    },
  },
};

export const CATEGORIES: { id: NodeCategory; label: string; color: string }[] = [
  { id: 'browser', label: 'Browser', color: '#3b82f6' },
  { id: 'interaction', label: 'Interaction', color: '#6366f1' },
  { id: 'wait', label: 'Wait', color: '#f59e0b' },
  { id: 'extraction', label: 'Extraction', color: '#10b981' },
  { id: 'logic', label: 'Logic', color: '#8b5cf6' },
  { id: 'data', label: 'Data', color: '#ec4899' },
  { id: 'utility', label: 'Utility', color: '#06b6d4' },
  { id: 'messaging', label: 'Messaging', color: '#14b8a6' },
  { id: 'command', label: 'Commands', color: '#f43f5e' },
];

export function getNodeDefinition(type: NodeType): NodeDefinition {
  return NODE_REGISTRY[type] || NODE_REGISTRY.navigate;
}
